name: Bug Report
description: Сообщить об ошибке
title: "[BUG]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Описание ошибки
      description: Что произошло?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
    validations:
      required: false